config/routes.rb
Rails.application.routes.draw do
  # deviseが提供するactionの内容を再設定する
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
    resources :users, only: :new
    
  root to: "foods#index"
  resources :foods do
    resources :comments, only: [:show, :create]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :category
  belongs_to :prefecture
  has_many   :comments, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :example
    validates :category_id
    validates :prefecture_id
    validates :price
    validates :image
    validates :user_id
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.includes(:user)
  end

  def new
    @food = Food.new()
  end

  def show
    @food = Food.find(params[:id])
    @comment = Comment.new
    @comments = Comment.includes(:user).order('created_at DESC')
  end

  def edit
    @food = Food.find(params[:id])
    if @food.user == current_user
      render :edit
    else
      redirect_to root_path
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.user == current_user
      @food.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to food_path
    else
      render :edit
    end
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :example, :category_id, :prefecture_id, :price, :image, :menue).merge(user_id: current_user.id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/edit.html.erb
<div class="foods-sell-contents">
<%= render "shared/header" %>
  <div class="foods-sell-main">
  <%= form_with(model: @food, url: food_path, local: true) do |f| %>
    <h2 class="foods-sell-title">店舗の情報を入力</h2>
    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 店舗名 %>
    <div class="new-foods">
      <div class="weight-bold-text">
        店舗名
      </div>
      <%= f.text_area :name, class:"foods-text", id:"item-name", placeholder:"店舗名", maxlength:"40" %>
      <%# 商品説明 %>
      <div class="foods-explain">
        <div class="weight-bold-text">
          店舗の説明
        </div>
        <%= f.text_area :example, class:"foods-text", id:"item-info", placeholder:"あいうえお" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 店舗の詳細 %>
    <div class="foods-detail">
      <div class="weight-bold-text">店舗の詳細</div>
    <%# カテゴリー %>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"food-category"}) %>
      </div>
    </div>
    <%# エリア %>
    <div class="foods-detail">
      <div class="weight-bold-text"></div>
      <div class="form">
        <div class="weight-bold-text">
          エリア
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"food-category"}) %>
      </div>
    </div>

    <%# 目安価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>目安予算</span>
      </div>
      <div class="price-content">
        <div class="price-text">
          <span>価格</span>
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_field :price, class:"price-input", id:"food-price", placeholder:"例）300" %>
      </div>
    </div>

    <%# 画像投稿 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        店舗・料理画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"food-image" %>
      </div>
    </div>

    <%# 送信ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "編集を投稿する",class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/foods/index.html.erb
<%= render "shared/header" %>
<div class="wrapper-out">
  <div class="wrapper">
    <div class="main">
      <div class="container">
        <ul class="food-lists">
          <% @foods.each do |food| %>
            <li class="list">
              <%= link_to food_path(food.id) do %>
                <div class="food-img-tag">
                  <%= image_tag food.image , class: "food-img" %> 
                </div>      
                <div class="food-info">
                  <%= food.name %>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/foods/new.html.erb
<div class="foods-sell-contents">
<%= render "shared/header" %>
  <div class="foods-sell-main">
  <%= form_with(model: @food, url: foods_path, local: true) do |f| %>
    <h2 class="foods-sell-title">店舗の情報を入力</h2>
    <%= render 'shared/error_messages', model: f.object %>
    
    <%# 店舗名 %>
    <div class="new-foods">
      <div class="weight-bold-text">
        店舗名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"foods-text", id:"item-name", placeholder:"店舗名", maxlength:"40" %>
      <%# 商品説明 %>
      <div class="foods-explain">
        <div class="weight-bold-text">
          店舗の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :example, class:"foods-text", id:"item-info", placeholder:"あいうえお" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 店舗の詳細 %>
    <div class="foods-detail">
      <div class="weight-bold-text">店舗の詳細</div>
    <%# カテゴリー %>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"food-category"}) %>
      </div>
    </div>
    <%# エリア %>
    <div class="foods-detail">
      <div class="weight-bold-text"></div>
      <div class="form">
        <div class="weight-bold-text">
          エリア
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"food-category"}) %>
      </div>
    </div>

    <%# おすすめ一品! %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>おすすめ一品！</span>
      </div>
      <div class="price-content">
        <div class="price-text">
          <span>料理</span>
        </div>
        <span class="sell-yen"></span>
        <%= f.text_field :menue, class:"price-input", id:"food-price", placeholder:"例）ロースカツ丼" %>
      </div>
    </div>

    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>目安予算</span>
      </div>
      <div class="price-content">
        <div class="price-text">
          <span>価格</span>
          <span class="indispensable">必須</span>
        </div>
        <span class="sell-yen">¥</span>
        <%= f.text_field :price, class:"price-input", id:"food-price", placeholder:"例）300" %>
      </div>
    </div>

    <%# 画像投稿 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        店舗・料理画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"food-image" %>
      </div>
    </div>

    <%# 送信ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する",class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/foods/show.html.erb
<div class="foods-show-contents">
<%= render "shared/header" %>
  <div class="foods-show-main">
  <%# 写真 %>
    <div class="img-example">
      <div class="show-img">
        <%= image_tag @food.image ,class:"food-box-img" %>
      </div>
      <%# 編集・削除ボタン %>
      <div class="action-example">
        <div class="delete-edit">
          <% if user_signed_in? %>
            <% if current_user.id == @food.user.id %>
              <div class="show-delete">
                <%= link_to '編集', edit_food_path(@food.id), method: :get, class: "button-delete" %>
              </div>
              <div class="show-edit">
                <%= link_to '削除', food_path(@food.id) , method: :delete, class:'button-edit' %>
              </div>
            <% end %>
          <% end %>
        </div>
        <%# 店舗説明 %>
        <div class="show-example">
          <div class="detail-text">
              店舗の感想
          </div>
          <div class="detail-value">
            <%= @food.example %>
          </div>
        </div>
      </div>
    </div>
    <%# 店舗名 %>
    <div class="food-shop">
      <div class="show-name"> 
        <div class="shop-text">
          店舗名
        </div>
        <div class="shop-name">
          <%= @food.name %>
        </div>
      </div>
    </div>
    <%# エリアと予算とおすすめ一品！ %>
    <div class="area-price">
      <div class="show-area">
        <ul>
          <li class="show-category">
            エリア
          </li>
          <li class="show-prefecture-category">
            <%= @food.prefecture.name %>
          </li>
        </ul>
      </div>
      <div class="show-price">
        <ul>
          <li class="show-category">
            予算
          </li>
          <li class="show-price-category">
            <%= converting_to_jpy(@food.price) %>
          </li>
        </ul>
      </div>
      <div class="show-price">
        <ul>
          <li class="show-category">
            おすすめ一品！
          </li>
          <li class="show-price-category">
            <%= @food.menue %>
          </li>
        </ul>
      </div>
    </div>
    <%# コメント機能 %>
    <div class="food-menue">
      <%= form_with(model:[@food, @comment], local: true) do |f| %>
        <div class="show-comment">
          <%= f.text_field :comment, class:"comment-text",  placeholder:"例）こんにちは"%>
          <%= f.submit "コメント送信", id:"comment-btn", class:"comment-btn" %>
        </div>
      <% end %>
      <div id="comments", class="comments-field">
        <h3 class="comment-list-text">＜ コメント一覧 ＞</h3>
        <% @comments.each do |comment| %>
          <li class="comments_list ">
            <%= comment.comment %>
            <%= comment.user.nickname %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= render "shared/footer" %>